---
sudo: false
language: ruby
cache:
- directories:
  - vendor/bundle
  - node_modules
rvm:
- '2.2'
- '2.1'
- 2.0.0
- 1.9.3
env:
- REDMINE_VERSION=2.6.1
- REDMINE_VERSION=2.5.3
- REDMINE_VERSION=2.4.7
- REDMINE_VERSION=master
matrix:
  allow_failures:
  - env: REDMINE_VERSION=master
  - rvm: '2.2'
install:
- export BUNDLE_GEMFILE=""
- export BUNDLE_PATH="$(pwd)/vendor/bundle"
- npm update
- ./redmine update
- bundle install --jobs=3 --retry=3 --path $BUNDLE_PATH
script:
- make all
- bundle exec rake spec
